[build]
  publish = "dist"
  command = "npm run build:netlify"

[build.environment]
  NETLIFY = "true"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Cross-Origin-Opener-Policy = "same-origin-allow-popups"
    Cross-Origin-Embedder-Policy = "unsafe-none"

[context.production]
  environment = { NETLIFY = "true" }

[context.deploy-preview]
  environment = { NETLIFY = "true" }

[context.branch-deploy]
  environment = { NETLIFY = "true" }
